### ISSUE TITLE
Include setuptools-scm as a build dependency for next release

### ISSUE THREAD

**Issue by bouweandela** [conda-forge/esmvalcore-feedstock#38]
Ref: https://github.com/ESMValGroup/ESMValCore/pull/1578

See e.g. [here](https://github.com/conda-forge/cmip6_preprocessing-feedstock/pull/8/files) for an example.

**Comment by schlunma** [comment]
It's already in there:

https://github.com/conda-forge/esmvalcore-feedstock/blob/3a83136e793420712dfbad412c3cd794dc08a323/recipe/meta.yaml#L26

(in `main` and `rc`)

So I guess we can close this?
