### ISSUE TITLE
New (dependency) pins to keep in mind for v2.8

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/esmvalcore-feedstock#53]
@remi-kazeroni these are the pins we have to change for 2.8; I also have to add you as a repo admin, and I'll do that immediately after I send off this issue.

```
iris >=3.4.0  # existing, different pin

NOT compilers  # new
filelock  # new
iris-esmf-regrid  # new
packaging  # new
py-cordex  # new

```

`compilers` has been removed since we dropped support for `vprof` as @bouweandela mentioned

**Comment by remi-kazeroni** [comment]
Thanks a lot @valeriupredoi for opening these 2 issues! Out of curiosity, what's the best approach to derive this list of changed pins/dependencies? Is that by checking the recent history of the [environment.yml](https://github.com/ESMValGroup/ESMValCore/blame/main/environment.yml) except for changes related to the doc build? If so, the list looks good to me 👍

**Comment by valeriupredoi** [comment]
@remi-kazeroni that indeed, and keeping an eye on the package builds (the Azure CI tests) when we release, see if it fails due to some missing package in `recipe.yml`. Looks like the conda bot is sleeping again, that issue should have triggered an automatic PR - I'll look into it

**Comment by valeriupredoi** [comment]
OK Remi, you are now a maintainer here, welcome to the Forge, bud! :hammer_and_pick:

**Comment by valeriupredoi** [comment]
closing this since we now folded all these in 2.8.0rc1 in #57
