### ISSUE TITLE
TODO for v2.8.0 release off the rc

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/esmvalcore-feedstock#58]
@remi-kazeroni this is the procedure for the actual release, as you, @zklaus and myself have just discussed:

- after the last rc has been released, create a feature branch off `main`
- merge the most recent version of the `rc` branch into that feature branch
- make sure the build config file https://github.com/conda-forge/esmvalcore-feedstock/blob/rc/recipe/conda_build_config.yaml is not pointing to `esmvalcore_rc` (or it's not there at all), change to 2.8.0, update `sha`, rerender, and check build tests
- make that the release branch and merge into `main`

(PS we may want to plop these sort of instructions in our dox)

**Comment by remi-kazeroni** [comment]
Thanks @valeriupredoi! Maybe that procedure could go into the README of this repo, or into a CONTRIBUTING.md? Or do you think it would make more sense to have it in our Tool/Core RTD?

**Comment by valeriupredoi** [comment]
probably in the release documentation indeed, bud. Let me open an issue about it :+1:
